_base_: './continual_default.yml'

data:
  dataset: ourdata_ego
  clip_length: 4

test:
  testonly: true
  ourdata:
    metadata: ${data.metapath}association_test_hard.json

resume: null
output: ./exps/test_egoonly_continual/

continual:
  checkpoint_dir: ./exps/train_egoonly_continual/

