_base_: '../continual_default_fixbcb.yml'

data:
  dataset: ourdata_exo
  clip_length: 4

test:
  testonly: true
  ourdata:
    metadata: ${data.metapath}association_test_hard.json

resume: null
output: ./exps/multi_seed_cl_fixbcb/test_exoonly_seed2/

continual:
  checkpoint_dir: ./exps/multi_seed_cl_fixbcb/train_exoonly_seed2/

