output_root: temporal_action_segmentation_benchmark/exps/continual_er/egoexo_ego
video_to_task_path: <DATA_ROOT>/video_to_task.npy

path_data: temporal_action_segmentation_benchmark/tas_annotation
feature_path: <DATA_ROOT>/EgoExoLearn/i3d_rgb_features/

exp_type: ego-exo-cotraining-ego
eval_split: val
num_tasks: 4
epochs_per_task: 150
val_every: 0
seed: 42
max_train_videos_per_task: null
max_eval_videos: null

feat_sample_rate: 1
label_sample_rate: 1
all_sample_rate: 5
features_dim: 1024
use_target: none


dataset: egobridge
lr: 0.0005
num_epochs: 150
DA_adv: none
DA_adv_video: none
DA_ent: none
use_attn: none
DA_dis: none
DA_ens: none
SS_video: none
method_centroid: none
use_best_model: none
num_seg: 1
beta: [-2.0, -2.0]
iter_max_beta: [2000, 1400]
iter_max_gamma: 2000
iter_max_nu: 37500
mu: 0.0
eta: 0.0

continual_algorithm: er
continual_algorithm_buffer_ratio: 0.2
continual_algorithm_replay_batch_ratio: 0.2

