_base_: '../continual_default_fixbcb_ep10.yml'

data:
  dataset: ourdata_egoexo
  clip_length: 4

test:
  testonly: true
  ourdata:
    metadata: ${data.metapath}association_test_hard.json

resume: null
output: ./exps/multi_seed_cl_fixbcb_ep10/test_egoexo_seed0/

continual:
  checkpoint_dir: ./exps/multi_seed_cl_fixbcb_ep10/train_egoexo_seed0/


