_base_: '../continual_default_fixbcb_ep10.yml'

data:
  dataset: ourdata_egoexo
  clip_length: 4

train:
  batch_size: 32
  seed: 1

test:
  testonly: false

resume: <DATA_ROOT>/weights/LaViLA/clip_openai_timesformer_base.narrator_rephraser.ep_0001.md5sum_02dbb9.pth
output: ./exps/multi_seed_cl_fixbcb_ep10/train_egoexo_seed1/



